blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/d99kris/nmail/discussions/new?category=ideas
    about: Suggest a new feature by creating a new discussion.
